---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: paulanunesdasilva85_gmail.com#EXT#
  annotations:
    microsoft.com/email: "paulanunesdasilva85_gmail.com#EXT#@paulanunesdasilva85gmail.onmicrosoft.com"
    graph.microsoft.com/user-id: "paulanunesdasilva85"
spec:
  profile:
    displayName: Paula Silva
    email: "paulanunesdasilva85_gmail.com#EXT#@paulanunesdasilva85gmail.onmicrosoft.com"
  memberOf: [guests]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: paulasilva
  annotations:
    microsoft.com/email: "paulasilva@microsoft.com"
spec:
  profile:
    displayName: Paula Silva
    email: "paulasilva@microsoft.com"
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
